You are hired by an international bank with millions of customers spread all around Europe mainly in, three countries, Spain, France and Germany. In the last six months the bank detected that the number of people leaving the bank started to increase, so they decided to take measures. 

The bank decided to take a small sample of 10,000 of their customers and retrieve some information.
For six months they followed the behaviour of these 10,000 customers and analysed which stayed and who left the bank. 

Therefore, they want you to develop a model that can measure the probability of a customer leaving the bank.

### Start by importing numpy and pandas -- 

In [51]:
import pandas as pd
import numpy as np

## Part 1 - Data Preprocessing

**Import the dataset Bank_customers.csv**

**Perform all required data preprocessing steps, until you have your train set and yout test set.**

In [52]:
df = pd.read_csv('Bank_customers.csv')
categorical_features = ['Geography','Gender']
final_df = pd.get_dummies(df,columns=categorical_features,drop_first=True)
final_df

RowNumber  CustomerId    Surname  CreditScore  Age  Tenure    Balance  \
0             1    15634602   Hargrave          619   42       2       0.00   
1             2    15647311       Hill          608   41       1   83807.86   
2             3    15619304       Onio          502   42       8  159660.80   
3             4    15701354       Boni          699   39       1       0.00   
4             5    15737888   Mitchell          850   43       2  125510.82   
...         ...         ...        ...          ...  ...     ...        ...   
9995       9996    15606229   Obijiaku          771   39       5       0.00   
9996       9997    15569892  Johnstone          516   35      10   57369.61   
9997       9998    15584532        Liu          709   36       7       0.00   
9998       9999    15682355  Sabbatini          772   42       3   75075.31   
9999      10000    15628319     Walker          792   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0                 1          1               1        101348.88       1   
1                 1          0               1        112542.58       0   
2                 3          1               0        113931.57       1   
3                 2          0               0         93826.63       0   
4                 1          1               1         79084.10       0   
...             ...        ...             ...              ...     ...   
9995              2          1               0         96270.64       0   
9996              1          1               1        101699.77       0   
9997              1          0               1         42085.58       1   
9998              2          1               0         92888.52       1   
9999              1          1               0         38190.78       0   

      Geography_Germany  Geography_Spain  Gender_Male  
0                     0                0            0  
1                     0                1            0  
2                     0                0            0  
3                     0                0            0  
4                     0                1            0  
...                 ...              ...          ...  
9995                  0                0            1  
9996                  0                0            1  
9997                  0                0            0  
9998                  1                0            1  
9999                  0                0            0  

[10000 rows x 15 columns]

In [53]:
# df.info()
X = final_df.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1) 
y = final_df['Exited']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [56]:
type(X_train)

pandas.core.frame.DataFrame

### Perform feature scaling

Use the StandardScaler class from sklearn.preprocessing. You can read more about it here https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

Use the fit_transform and the transform methods to perform feature scalng on your training set and your test set


In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

sc.fit(X_train,y_train)
sc.transform(X)
sc.fit_transform(X_test,y_test)

array([[-3.60237034e-02,  9.86670878e-04, -1.72917010e+00, ...,
         1.70776143e+00, -5.72218165e-01,  9.06973121e-01],
       [-1.32109201e+00, -4.76434722e-01, -1.04444065e+00, ...,
        -5.85561885e-01, -5.72218165e-01,  9.06973121e-01],
       [ 6.84533946e-02, -5.71919000e-01, -3.59711204e-01, ...,
        -5.85561885e-01,  1.74758521e+00,  9.06973121e-01],
       ...,
       [-4.64379805e-01, -3.80950443e-01,  3.25018245e-01, ...,
        -5.85561885e-01, -5.72218165e-01,  9.06973121e-01],
       [ 6.22182014e-01, -1.52676179e+00,  1.00974769e+00, ...,
         1.70776143e+00, -5.72218165e-01,  9.06973121e-01],
       [ 2.09530909e+00,  2.57906219e+00, -1.72917010e+00, ...,
         1.70776143e+00, -5.72218165e-01, -1.10256851e+00]])

## Part 2 - Now let's create the ANN!

### Importing the Keras libraries and packages
You are going to use the Sequential model. You can read more about it here https://keras.io/models/sequential/

In [58]:
import keras
from keras.models import Sequential
from keras.layers import Dense

import **Dropout** to be used when adding layers: A Simple Way to Prevent Neural Networks from Overfitting

Dropout consists in randomly setting a fraction rate of input units to 0 at each update during training time, which helps prevent overfitting.

Arguments:

rate: float between 0 and 1. Fraction of the input units to drop.

In [59]:
from keras.layers import Dropout

### Start by declaring a sequential model named classifier

In [60]:
classifier = Sequential()

### Add the input layer and the first hidden layer using the .add() method

Use the **Dense** method that takes the following arguments: 

**units**: dimensionality of the output space.

**activation**: Activation function to use (relu for hidden layers, and sigmoid for output layer). 

**kernel_initializer**: Initializer for the kernel weights matrix.

In addition, add the argument **input_dim**: dimension of the input layer, to be passed for the first hidden layer.

In [61]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

**Apply Dropout to the input units for regularization with a probability of 0.1**

In [62]:
classifier.add(Dropout(0.1))

### Add the second hidden layer made of 6 units

In [63]:
classifier.add(Dense(units = 6, activation = 'relu',kernel_initializer = 'uniform'))

### Add the output layer 

In [64]:
classifier.add(Dense(units = 1, activation = 'sigmoid',kernel_initializer = 'uniform'))

### Compiling the ANN

Before training a model, you need to configure the learning process, which is done via the **compile** method. 

It receives three arguments: an **optimizer** (use 'adam'), a **loss** function (use 'binary_crossentropy'), and list of **metrics** (use the 'accuracy'). 

In [65]:
classifier.compile(optimizer = 'adam', loss  = 'binary_crossentropy', metrics = ['accuracy'])

### Fitting the ANN to the Training set

Keras models are trained on Numpy arrays of input data and labels. For training a model, you will typically use the **fit** function.

Arguments: 

Input data, Target data,

**batch_size**: Number of samples per gradient update 

**epochs**: Number of iterations on the dataset

You are going to train your model using a batch size of 10, and 100 epochs 

In [66]:
classifier.fit(X_train,y_train,batch_size = 10, epochs = 100)

Epoch 1/100
7000/7000 [==============================] - 2s 218us/step - loss: 0.5457 - accuracy: 0.7986
Epoch 2/100
7000/7000 [==============================] - 1s 131us/step - loss: 0.5192 - accuracy: 0.8020
Epoch 3/100
7000/7000 [==============================] - 1s 131us/step - loss: 0.5144 - accuracy: 0.8020
Epoch 4/100
7000/7000 [==============================] - 1s 132us/step - loss: 0.5079 - accuracy: 0.8020
Epoch 5/100
7000/7000 [==============================] - 1s 139us/step - loss: 0.5020 - accuracy: 0.8020
Epoch 6/100
7000/7000 [==============================] - 1s 132us/step - loss: 0.4990 - accuracy: 0.8020
Epoch 7/100
7000/7000 [==============================] - 1s 134us/step - loss: 0.4960 - accuracy: 0.8020
Epoch 8/100
7000/7000 [==============================] - 1s 146us/step - loss: 0.4934 - accuracy: 0.8020
Epoch 9/100
7000/7000 [==============================] - 1s 187us/step - loss: 0.4937 - accuracy: 0.8020
Epoch 10/100
7000/7000 [==============================]

7000/7000 [==============================] - 1s 139us/step - loss: 0.4910 - accuracy: 0.8020
Epoch 79/100
7000/7000 [==============================] - 1s 130us/step - loss: 0.4909 - accuracy: 0.8020
Epoch 80/100
7000/7000 [==============================] - 1s 130us/step - loss: 0.4906 - accuracy: 0.8020
Epoch 81/100
7000/7000 [==============================] - 1s 128us/step - loss: 0.4908 - accuracy: 0.8020
Epoch 82/100
7000/7000 [==============================] - 1s 127us/step - loss: 0.4910 - accuracy: 0.8020
Epoch 83/100
7000/7000 [==============================] - 1s 129us/step - loss: 0.4908 - accuracy: 0.8020
Epoch 84/100
7000/7000 [==============================] - 1s 158us/step - loss: 0.4909 - accuracy: 0.8020
Epoch 85/100
7000/7000 [==============================] - 1s 148us/step - loss: 0.4905 - accuracy: 0.8020
Epoch 86/100
7000/7000 [==============================] - 1s 127us/step - loss: 0.4912 - accuracy: 0.8020
Epoch 87/100
7000/7000 [==============================] - 1

## Part 3 - Making predictions and evaluating the model



### Predicting the Test set results

#### Use the .predict(input data) method. It generates output predictions for the input samples.

In [67]:
res = classifier.predict(X_test)
res

array([[0.24532558],
       [0.24532558],
       [0.1386362 ],
       ...,
       [0.1386362 ],
       [0.24532558],
       [0.24532558]], dtype=float32)

#### Since the output value of a sigmoid function varies between 0 and 1. Choose a threshold (use 0.5) to assign a value of 1 for predictions higher than 0.5, and 0 otherwise.

In [68]:
res = (res > 0.5)
res

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

### Confusion Matrix

In [69]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, res)
cm

array([[2349,    0],
       [ 651,    0]], dtype=int64)

## Predicting a single new observation

Predict if the customer with the following informations will leave the bank:
Geography : France  -  Credit score : 600  -  Gender : Male  -  Age : 40  -  Tenure : 3  -  Balance : 60000  -  Number of products : 2  -  Has credit card: Yes  -  Is an active memeber: Yes  -  Estimated salary : 50000

What is the output value of your classifier? is the customer going to leave the bank?

In [70]:
new_pred = classifier.predict(sc.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_pred = (new_pred > 0.5)

##  4 - Evaluating the ANN

You can use Sequential Keras models as part of your Scikit-Learn workflow via the wrappers found in keras library. More info can be found here https://keras.io/scikit-learn-api/

KerasClassifier Arguments :
    
build_fn should construct, compile and return a Keras model, which will then be used to fit/predict. 

sk_params: model parameters & fitting parameters

In [71]:
from keras.wrappers.scikit_learn import KerasClassifier

In [72]:
from sklearn.model_selection import cross_val_score

#### create the function that builds the architecture of the ANN

In [73]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier  #classifier is local to this function

#### Create an object inside this class named kclassifier that takes the previous function as arguments, and  the batch_size and the number of epochs

In [75]:
kclassifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 100) 

#### Use the cross_val_score function. Define an array that will contain the k-accuracies of the k-fold CV, name it accuracies.


In [78]:
accuracies = cross_val_score(estimator = kclassifier, X = X_train, y = y_train)

Epoch 1/100
4666/4666 [==============================] - 1s 269us/step - loss: 0.5631 - accuracy: 0.7960
Epoch 2/100
4666/4666 [==============================] - 1s 149us/step - loss: 0.5297 - accuracy: 0.7998
Epoch 3/100
4666/4666 [==============================] - 1s 173us/step - loss: 0.5225 - accuracy: 0.7998
Epoch 4/100
4666/4666 [==============================] - 1s 159us/step - loss: 0.5195 - accuracy: 0.7998
Epoch 5/100
4666/4666 [==============================] - 1s 156us/step - loss: 0.5154 - accuracy: 0.7998
Epoch 6/100
4666/4666 [==============================] - 1s 152us/step - loss: 0.5095 - accuracy: 0.7998
Epoch 7/100
4666/4666 [==============================] - 1s 153us/step - loss: 0.5076 - accuracy: 0.7998
Epoch 8/100
4666/4666 [==============================] - 1s 156us/step - loss: 0.5035 - accuracy: 0.7998
Epoch 9/100
4666/4666 [==============================] - 1s 173us/step - loss: 0.4993 - accuracy: 0.7998
Epoch 10/100
4666/4666 [==============================]

4666/4666 [==============================] - 1s 121us/step - loss: 0.4945 - accuracy: 0.7998
Epoch 79/100
4666/4666 [==============================] - 1s 118us/step - loss: 0.4944 - accuracy: 0.7998
Epoch 80/100
4666/4666 [==============================] - 1s 119us/step - loss: 0.4945 - accuracy: 0.7998
Epoch 81/100
4666/4666 [==============================] - 1s 119us/step - loss: 0.4953 - accuracy: 0.7998
Epoch 82/100
4666/4666 [==============================] - 1s 120us/step - loss: 0.4939 - accuracy: 0.7998
Epoch 83/100
4666/4666 [==============================] - 1s 118us/step - loss: 0.4949 - accuracy: 0.7998
Epoch 84/100
4666/4666 [==============================] - 1s 120us/step - loss: 0.4950 - accuracy: 0.7998
Epoch 85/100
4666/4666 [==============================] - 1s 119us/step - loss: 0.4940 - accuracy: 0.7998
Epoch 86/100
4666/4666 [==============================] - 1s 128us/step - loss: 0.4950 - accuracy: 0.7998
Epoch 87/100
4666/4666 [==============================] - 1

Epoch 55/100
4667/4667 [==============================] - 1s 127us/step - loss: 0.4841 - accuracy: 0.8065
Epoch 56/100
4667/4667 [==============================] - 1s 123us/step - loss: 0.4838 - accuracy: 0.8065
Epoch 57/100
4667/4667 [==============================] - 1s 120us/step - loss: 0.4837 - accuracy: 0.8065
Epoch 58/100
4667/4667 [==============================] - 1s 118us/step - loss: 0.4835 - accuracy: 0.8065
Epoch 59/100
4667/4667 [==============================] - 1s 116us/step - loss: 0.4834 - accuracy: 0.8065
Epoch 60/100
4667/4667 [==============================] - 1s 118us/step - loss: 0.4833 - accuracy: 0.8065
Epoch 61/100
4667/4667 [==============================] - 1s 117us/step - loss: 0.4832 - accuracy: 0.8065
Epoch 62/100
4667/4667 [==============================] - 1s 120us/step - loss: 0.4832 - accuracy: 0.8065
Epoch 63/100
4667/4667 [==============================] - 1s 117us/step - loss: 0.4829 - accuracy: 0.8065
Epoch 64/100
4667/4667 [======================

4667/4667 [==============================] - 1s 196us/step - loss: 0.4998 - accuracy: 0.7997
Epoch 32/100
4667/4667 [==============================] - 1s 191us/step - loss: 0.5013 - accuracy: 0.7997
Epoch 33/100
4667/4667 [==============================] - 1s 210us/step - loss: 0.5003 - accuracy: 0.7997
Epoch 34/100
4667/4667 [==============================] - 1s 190us/step - loss: 0.4997 - accuracy: 0.7997
Epoch 35/100
4667/4667 [==============================] - 1s 164us/step - loss: 0.4997 - accuracy: 0.7997
Epoch 36/100
4667/4667 [==============================] - 1s 154us/step - loss: 0.5001 - accuracy: 0.7997
Epoch 37/100
4667/4667 [==============================] - 1s 161us/step - loss: 0.5001 - accuracy: 0.7997
Epoch 38/100
4667/4667 [==============================] - 1s 180us/step - loss: 0.4989 - accuracy: 0.7997
Epoch 39/100
4667/4667 [==============================] - 1s 170us/step - loss: 0.4988 - accuracy: 0.7997
Epoch 40/100
4667/4667 [==============================] - 1

#### Calculate the mean and the varince of your accuracies

In [80]:
mean = accuracies.mean()
mean

0.8019993702570597

In [81]:
variance = accuracies.std()
variance

0.006385991401441906

## Part 5 - Tuning the ANN (something for you to work on at home, if you want)

In [25]:
from sklearn.model_selection import GridSearchCV
